import Head from "next/head";
import { Header } from "../components/Header/Header";
import { Sidebar } from "../components/Sidebar/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <div className="flex">
          <Sidebar />
          <div className="w-full h-[700px] ml-[240px]">
            <h1>test</h1>
          </div>
        </div>
      </div>
    </>
  );
}
